version: '3.7'

services:
  redis:
    image: redis:alpine

  mongo:
    image: mongo:latest

  postgres:
    image: postgres:alpine

  cliphpy:
    build:
      context: .
      dockerfile: development.Dockerfile
    links:
      - redis
      - mongo
      - postgres
    volumes:
      - $PWD:/usr/src/app
    command: sleep 9999999999999
